name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  Build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build