name: Testing

on:
  pull_request:
    branches:
      - master

jobs:
  Test_with_jest:
    name: Running tests with jest
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
      
      - name: Generate Prisma Types
        run: yarn prisma generate
      
      - name: Run tests
        run: yarn test
        env:
          SKIP_ENV_VALIDATION: true
          
  Test_with_docker_compose:
    name: Testing
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.test.yml"
          compose-flags: "-d --build"
        env:
          AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
              
      - name: Run test
        run: docker exec proffice-app /bin/bash -c yarn test
